### ISSUE TITLE
Make Comment Counter Clearer (suggestion)

### ISSUE THREAD

**Issue by MaximilianEmel** [jjcm/nonio#131]
In the current state, the comment counter is hard to parse in the post list. It should be nearer the other info, and generally made easier to see quicker, and relate to what post it's referring to.

**Comment by jjcm** [comment]
Updated! It should be clearer now: 
![image](https://github.com/jjcm/nonio/assets/50971/c470ca1d-60e2-4016-ba5d-121b987b5ea2)
