### ISSUE TITLE
Un-up/downvoting Comments Nonfunctional

### ISSUE THREAD

**Issue by MaximilianEmel** [jjcm/nonio#139]
When Un-up/downvoting a comment, it doesn't tell the server.

**Comment by jjcm** [comment]
I can't seem to recreate? What page are you seeing this on?

**Comment by MaximilianEmel** [comment]
https://github.com/jjcm/nonio/assets/19846453/07d23829-5b54-4053-8fec-400046fd56d3

**Comment by jjcm** [comment]
Ohhhh gotchya. I missed the “un” element in the title of this bug. Thank
you for the video, that helped a lot.
