### ISSUE TITLE
[Bug] Parts of financials page fails to load, can't add money.

### ISSUE THREAD

**Issue by ashirviskas** [jjcm/nonio#144]
I would like to support this project, but after choosing $0 tier subscription, every time I go to [financials](https://non.io/admin/financials) page and click on `Change Subscription Amount`, it only returns this:

```
GET https://api.non.io/stripe/subscription 500 (Internal Server Error)
error: "no customer for the user"
```

**Comment by jjcm** [comment]
Heya @ashirviskas - subscriptions should now be working on that page.
