### ISSUE TITLE
Overeager Input Check

### ISSUE THREAD

**Issue by MaximilianEmel** [jjcm/nonio#145]
When there's an input check, such as checking if a username is available, it happens on every keypress (e.g. pressing Shift, without adding anything), so it checks more often than it needs to.

**Comment by jjcm** [comment]
Yea I should probably debounce this as well, i.e. set up a 300ms rotating window and not retry until a user has stopped typing for that amount of time.

**Comment by jjcm** [comment]
Fixed with @Wetbikeboy2500's changes!
